exclude: ['email_welcome.html', 'email_welcome.mjml', 'email_content.html', 'email_content.mjml', 'email_product_issue.html', 'email_product_issue.mjml']
title: "매거진 입맛"
description: "한 사람을 구축하는 건 무수히 쌓인 사적 취향이 아닐까. 매거진 입맛은 이를 알아보기 위한 실험장입니다. UX 디자인, 위스키, 소설. 디자이너 이준환의 읽을 만한 취향들이 여기 있습니다."
email: dewberryneun@gmail.com
author: "이준환"
url: "https://dewberry9.github.io"
cdn_url: "https://cdn.jsdelivr.net/gh/dewberry9/dewberry9.github.io"
show_excerpts: true
collections_dir: collections
collections:
    product_design:
        output: true
    drink:
        output: true
    read:
        output: true

# Build settings
markdown: kramdown
pagination:
    enabled: true
    collection: all
    per_page: 11
    limit: 0
    sort_field: "date"
    sort_reverse: true
    trail: 
        before: 2
        after: 2
    title: ':title :num페이지'
feed:
    url: "https://dewberry9.github.io"
plugins:
  - jekyll-feed
  - jekyll-paginate-v2