title: "글공간 도각도각"
description: "UX 디자인과 술을 비롯해서 좋아하는 것들에 대해 적습니다. 종종 소설을 씁니다. 글공간 도각도각은 누구나 찾아올 수 있고, 머무를 수 있고, 떠날 수 있는 곳입니다."
email: dewberryneun@gmail.com
author: "이준환"
url: "https://dewberry9.github.io"
show_excerpts: true
timezone: Asia/Seoul
# Build settings
markdown: kramdown
pagination:
    enabled: true
    per_page: 9
    limit: 0
    sort_field: "date"
    sort_reverse: true
feed:
    url: "https://dewberry9.github.io"
plugins:
  - jekyll-feed
  - jekyll-paginate-v2