exclude: ['email_welcome.html', 'email_welcome.mjml']
title: "매거진 입맛"
description: "디자이너 이준환의 읽을 만한 취향들. 매거진 입맛 - 디자인 / 입맛리뷰 / 소설"
email: dewberryneun@gmail.com
author: "이준환"
url: "https://dewberry9.github.io"
cdn_url: "https://cdn.jsdelivr.net/gh/dewberry9/dewberry9.github.io"
show_excerpts: true
# Build settings
markdown: kramdown
pagination:
    enabled: true
    per_page: 11
    limit: 0
    sort_field: "date"
    sort_reverse: true
    trail: 
        before: 2
        after: 2
feed:
    url: "https://dewberry9.github.io"
plugins:
  - jekyll-feed
  - jekyll-paginate-v2