exclude: ['email_welcome.html', 'email_welcome.mjml', 'email_content.html', 'email_content.mjml']
title: "매거진 입맛"
description: "디자이너 이준환의 읽을 만한 취향들, 매거진 입맛 - 책, 술 그밖에 삶의 즐거움 리뷰 / UX, 비즈니스, 프레임워크, 프로덕트 디자인의 모든 것"
email: dewberryneun@gmail.com
author: "이준환"
url: "https://dewberry9.github.io"
cdn_url: "https://cdn.jsdelivr.net/gh/dewberry9/dewberry9.github.io"
show_excerpts: true
# Build settings
markdown: kramdown
pagination:
    enabled: true
    per_page: 11
    limit: 0
    sort_field: "date"
    sort_reverse: true
    trail: 
        before: 2
        after: 2
feed:
    url: "https://dewberry9.github.io"
plugins:
  - jekyll-feed
  - jekyll-paginate-v2